[project]
name = "odata-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aioredis>=2.0.1",
    "psycopg2-binary>=2.9.11",
    "redis>=7.0.1",
    "upstash-redis>=1.5.0",
]
